name: CI Check

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Run Add-on Linter"
        uses: "frenck/action-addon-linter@v2"